# Please note that we should not be using container-based infrastructure
# because Chrome requires a lot of shared memory and Travis does not allow
# use host's /dev/shm.
sudo: required
dist: trusty
cache: bundler
notifications:
  recipients:
    - titusfortner@gmail.com
before_script:
  - support/travis.sh
script: bundle exec rake $RAKE_TASK

_version:
  four: &four
    language: ruby
    rvm: 2.4.1

_browsers:
  chrome: &chrome
     addons:
       chrome: stable

matrix:
  include:
      - env: RAKE_TASK=spec:chrome
        <<: *four
        <<: *chrome
